// <auto-generated />
namespace AuctionAppDemo3.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AuctionItemAndBid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuctionItemAndBid));
        
        string IMigrationMetadata.Id
        {
            get { return "202112161722303_AuctionItemAndBid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
